services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - todo_network

  backend:
    build:
      context: ./backend
      target: production
    container_name: todo_backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=todo_user
      - DB_PASSWORD=todo_password
      - DB_NAME=todo_app
      - JWT_SECRET=production-jwt-secret-change-this-in-real-deployment
      - JWT_EXPIRES_IN=1d
    ports:
      - "3004:3000"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo_network

volumes:
  mysql_data:

networks:
  todo_network:
    driver: bridge